export const ANALYTICS_EVENTS = [
  'bot.start_received',
  'miniapp.open_attempt',
  'miniapp.tg_context_detected',
  'miniapp.initdata_present',
  'miniapp.bootstrap_started',
  'miniapp.bootstrap_succeeded',
  'miniapp.bootstrap_failed',
  'miniapp.first_rendered',
  'miniapp.boot_timeout',
  'miniapp.fatal_render_error',
  'wishlist.created',
  'wishlist.deleted',
  'wish.created',
  'wish.edited',
  'wish.deleted',
  'wish.completed',
  'import.started',
  'import.succeeded',
  'import.failed',
  'import.bot_started',
  'import.bot_succeeded',
  'import.bot_failed',
  'guest.view_opened',
  'reservation.succeeded',
  'reservation.cancelled',
  'share.token_generated',
  'subscription.cancelled',
  'payment.pre_checkout_rejected',
  'showcase.editor_opened',
  'showcase.cover_uploaded',
  'showcase.cover_removed',
  'showcase.saved',
  'showcase.published',
  'showcase.preview_opened',
  'showcase.share_clicked',
  'showcase.paywall_viewed',
  'showcase.upgrade_clicked',
  'public_profile.viewed',
  'public_profile.wishlist_opened',
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[number];
