export const ANALYTICS_EVENTS = [
  'bot.start_received',
  'miniapp.open_attempt',
  'miniapp.tg_context_detected',
  'miniapp.initdata_present',
  'miniapp.bootstrap_started',
  'miniapp.bootstrap_succeeded',
  'miniapp.bootstrap_failed',
  'miniapp.first_rendered',
  'miniapp.boot_timeout',
  'miniapp.fatal_render_error',
  'wishlist.created',
  'wishlist.deleted',
  'wish.created',
  'wish.edited',
  'wish.deleted',
  'wish.completed',
  'import.started',
  'import.succeeded',
  'import.failed',
  'import.bot_started',
  'import.bot_succeeded',
  'import.bot_failed',
  'guest.view_opened',
  'reservation.succeeded',
  'reservation.cancelled',
  'share.token_generated',
  'subscription.cancelled',
  'payment.pre_checkout_rejected',
  'showcase.editor_opened',
  'showcase.cover_uploaded',
  'showcase.cover_removed',
  'showcase.saved',
  'showcase.published',
  'showcase.preview_opened',
  'showcase.share_clicked',
  'showcase.paywall_viewed',
  'showcase.upgrade_clicked',
  'public_profile.viewed',
  'public_profile.wishlist_opened',

  // ===== Referral program =====
  // See /mockups/referral-program.html S11 for the full spec.
  // Inviter entry points
  'referral.entry_point_impression',
  'referral.entry_point_clicked',
  'referral.home_banner_dismissed',
  'referral.screen_opened',
  'referral.rules_opened',
  'referral.history_opened',
  // Share flow
  'referral.share_action_sheet_opened',
  'referral.link_copied',
  'referral.share_intent',
  'referral.share_completed',
  'referral.share_failed',
  'referral.reminder_drafted',
  // Pre-attribution (bot /start)
  'referral.start_command_received',
  'referral.code_resolved',
  'referral.code_invalid',
  'referral.payload_missing',
  'referral.landing_viewed',
  // Invitee funnel
  'referral.onboarding_started',
  'referral.onboarding_step_viewed',
  'referral.first_wishlist_created',
  'referral.first_item_created',
  'referral.qualification_criteria_met',
  // Attribution lifecycle
  'referral.attributed',
  'referral.attribution_rejected_on_write',
  'referral.pending_activation',
  'referral.qualified',
  'referral.qualification_timeout',
  'referral.rewarded',
  'referral.reward_grant_failed',
  'referral.rejected',
  // Fraud signals (per-signal events)
  'referral.fraud_signal_ip_cluster',
  'referral.fraud_signal_device_fingerprint',
  'referral.fraud_signal_velocity',
  'referral.fraud_signal_inactive_invitee',
  'referral.fraud_signal_same_tz_cluster',
  'referral.fraud_signal_self_referral',
  'referral.fraud_signal_suspicious_onboarding',
  'referral.fraud_signal_account_age_delta',
  'referral.fraud_score_calculated',
  'referral.fraud_review_queued',
  'referral.fraud_resolved',
  'referral.fraud_cluster_created',
  'referral.fraud_cluster_grew',
  'referral.fraud_false_positive_confirmed',
  'referral.fraud_false_negative_confirmed',
  'referral.reward_revoked',
  // Silent failures & UI errors
  'referral.code_generation_failed',
  'referral.screen_load_failed',
  'referral.history_load_failed',
  'referral.deeplink_open_failed',
  'referral.landing_render_blocked',
  'referral.banner_impression_but_no_click_session',
  'referral.client_js_error',
  // Race conditions & edge
  'referral.concurrent_attribution_blocked',
  'referral.qualification_fired_after_timeout',
  'referral.reward_granted_after_revoke',
  'referral.duplicate_start_command',
  'referral.attribution_invariant_violation',
  'referral.invitee_deleted_account_before_qualify',
  'referral.inviter_deleted_account_after_qualify',
  'referral.clock_skew_detected',
  // Reward grant mechanics
  'referral.cap_check_performed',
  'referral.pro_subscription_extended',
  'referral.pro_subscription_extend_failed',
  'referral.idempotency_hit',
  'referral.admin_manual_grant',
  // Bot notification health
  'referral.bot_notification_sent',
  'referral.bot_notification_delivery_failed',
  'referral.bot_notification_rate_limit_applied',
  'referral.bot_notification_dropped',
  'referral.bot_notification_opened',
  // Config & reproducibility
  'referral.config_changed',
  'referral.config_fetch_failed',
  'referral.experiment_assigned',
  'referral.experiment_exposure',
  'referral.feature_flag_evaluated',
  // Monetization impact (delayed attribution)
  'referral.inviter_converted_to_paid_after_bonus',
  'referral.invitee_converted_to_paid',
  'referral.invitee_retained_d7',
  'referral.invitee_retained_d30',
  // Celebration UI
  'referral.celebration_viewed',
  'referral.celebration_cta_clicked',

  // ===== Birthday Reminders =====
  // Settings (writes from Mini App)
  'birthday.settings_opened',
  'birthday.friend_reminders_enabled',
  'birthday.friend_reminders_disabled',
  'birthday.owner_reminders_enabled',
  'birthday.owner_reminders_disabled',
  'birthday.audience_changed',
  'birthday.advanced_windows_enabled',
  'birthday.advanced_windows_disabled',
  'birthday.primary_wishlist_set',
  'birthday.primary_wishlist_cleared',
  'birthday.custom_message_saved',
  'birthday.custom_message_cleared',
  'birthday.receiving_enabled',
  'birthday.receiving_disabled',
  // Opt-in flow (after first save of birthday)
  'birthday.optin_shown',
  'birthday.optin_accepted',
  'birthday.optin_dismissed',
  // Mute / unmute
  'birthday.mute_added',
  'birthday.mute_removed',
  // Pro paywall
  'birthday.paywall_shown',
  'birthday.paywall_converted',
  'birthday.pro_required_hit',
  // Scheduler (server-side)
  'birthday.scheduler_run_started',
  'birthday.scheduler_run_completed',
  'birthday.scheduler_run_failed',
  'birthday.candidate_found',
  'birthday.delivery_created',
  'birthday.delivery_sent',
  'birthday.delivery_skipped',
  'birthday.delivery_deferred',
  'birthday.delivery_failed',
  'birthday.delivery_retry',
  // Bot side
  'birthday.bot_message_sent',
  'birthday.bot_message_failed',
  'birthday.bot_cta_clicked',
  'birthday.bot_mute_clicked',
  // Mini App attribution (deep-link → in-app)
  'birthday.deeplink_opened',
  'birthday.deeplink_resolve_failed',
  'birthday.banner_seen',
  'birthday.banner_dismissed',
  'birthday.banner_cta_clicked',
  'birthday.public_wishlist_opened',
  'birthday.public_profile_opened',
  'birthday.item_opened',
  'birthday.item_reserved',
  'birthday.secret_reservation_clicked',
  'birthday.gift_completed',
  'birthday.subscribe_clicked',
  // Owner attribution (post-owner-reminder behavior)
  'birthday.owner_update_wishlist_opened',
  'birthday.owner_item_added',
  'birthday.owner_wishlist_made_public',
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[number];
