-- AlterEnum
ALTER TYPE "ItemStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "ItemStatus" ADD VALUE IF NOT EXISTS 'DELETED';

-- AlterTable
ALTER TABLE "Wishlist" ADD COLUMN IF NOT EXISTS "deadline" TIMESTAMP(3);
